// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToFavourites(arg1) {
  return window['go']['main']['App']['AddToFavourites'](arg1);
}

export function AlignTags(arg1) {
  return window['go']['main']['App']['AlignTags'](arg1);
}

export function DeleteFavouriteItem(arg1) {
  return window['go']['main']['App']['DeleteFavouriteItem'](arg1);
}

export function ListFavouriteItemTags(arg1) {
  return window['go']['main']['App']['ListFavouriteItemTags'](arg1);
}

export function LoadCatalog() {
  return window['go']['main']['App']['LoadCatalog']();
}

export function LoadFavourites() {
  return window['go']['main']['App']['LoadFavourites']();
}
