// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddToFavourites(arg1:number):Promise<void>;

export function AlignTags(arg1:number):Promise<void>;

export function DeleteFavouriteItem(arg1:number):Promise<void>;

export function ListFavouriteItemTags(arg1:number):Promise<Array<models.TagResponse>>;

export function LoadCatalog():Promise<Array<models.CatalogItem>>;

export function LoadFavourites():Promise<Array<models.FavouriteItem>>;
